### PR TITLE
Introduced configurable entry format

### PR DESCRIPTION
**Pull request by witx98**
### logchange-config.yml
```yml
    templates:
        entry: "${prefix}${title} ${authors} ${links} ${issues} ${merge_requests}"
```

## Entry
```yml
title: Some change
authors:
  - name: Mateusz Witkowski
    nick: witx98
    url: https://github.com/witx98
issues:
  - 999
links:
  - name: Google
    url: https://google.com
merge_requests:
  - 1000
type: added # [added/changed/deprecated/removed/fixed/security/dependency_update/other]
```

### CHANGELOG.md
```md
[unreleased]
------------

### Added (1 change)

- Some change ([Mateusz Witkowski](https://github.com/witx98) @witx98) [Google](https://google.com) #999 !1000

```

### CODE REVIEW

**Comment by witx98** [comment]
@marwin1991

**Comment by marwin1991** [comment]
@witx98 greate work! Can we add info about it to README.md ?

**Comment by witx98** [comment]
@marwin1991 Sure, already updated

**Review by marwin1991 — APPROVED** [review]
approved

**Pull request merged**
