### PR TITLE
Aggregate version feature

### PR DESCRIPTION
**Pull request by witx98**
# Summary

This PR introduces functionality for generating an aggregated changelog version from multiple projects, as defined in the `aggregates` section of the `logchange-config.yml` configuration file (see the Setup section for detailed configuration instructions).

The new aggregate command accepts three parameters:

- `aggregateVersion` (required) – specifies the version to aggregate.
- `inputDir` (optional) – defines the directory containing the configuration file.
- `configFile` (optional) – specifies the name of the configuration file.

The command performs the following steps:

- Retrieves the `changelog` folder of the current project.
- Loads the configuration file, which defines the projects to aggregate.
- Creates a folder in the `changelog` directory for the version specified by `aggregateVersion`.
- Creates a temporary folder to store files from each aggregated project.
- For each project in the configuration, downloads a `.tar.gz` archive containing all project repository files.
- Extracts only the files from the project’s specified `input_dir`.
- Deletes the downloaded archives once extraction is complete.
- Filters extracted entries to include only those matching the specified `aggregateVersion`.
- Maps these entries to `ChangelogEntry` objects, organized into standard groups:
  - `added`, `changed`, `deprecated`, `removed`, `fixed`, `security`, `dependency_update`, `other`.
  - Entries are prefixed with the project name in the format `**PROJECT_NAME - **`.
  - Entries related to `configurations` and `important_notes` are also tagged with the respective project name.
- Aggregates all entries into a single `ChangelogVersion`:
  - The `version` number is defined by `aggregateVersion`.
  - The `releaseDate` is set to the latest release date among the projects or defaults to the current date if no release date is available.
  - Combines entries from all specified projects.
- Saves the aggregated `ChangelogVersion` in `changelog/vX.X.X/version-summary.md`.
- Cleans up by deleting the temporary folder and its contents.

## Setup:

<details><summary>Details</summary>

### Input directory structure:

```
changelog/
├── unreleased/
└── logchange-config.yml
```
### Input config:

```
aggregates:
    projects:
        - name: hofund
          url: https://github.com/logchange/hofund/archive/refs/heads/master.tar.gz
          type: tar.gz # currently only tar.gz is supported
          input_dir: changelog # the name where dirs with versions are stored for this project
        - name: logchange
          url: https://github.com/logchange/logchange/archive/refs/heads/main.tar.gz
          type: tar.gz
          input_dir: changelog
```

### Input command:

```
 mvn logchange:aggregate -DaggregateVersion="0.4.0" 
```

</details>

## Result:

<details><summary>Details</summary>

### Output directory structure:

```
changelog/
├── unreleased/
├── v0.4.0/
│   └── version-summary.md
└── logchange-config.yml
```

### Output file `version-summary.md`:

```
<!-- @formatter:off -->
<!-- noinspection -->
<!-- Prevents auto format, for JetBrains IDE File > Settings > Editor > Code Style (Formatter Tab) > Turn formatter on/off with markers in code comments  -->

<!-- This file is automatically generate by logchange tool 🌳 🪓 => 🪵 -->
<!-- Visit https://github.com/logchange/logchange and leave a star 🌟 -->
<!-- !!! ⚠️ DO NOT MODIFY THIS FILE, YOUR CHANGES WILL BE LOST ⚠️ !!! -->


[0.4.0] - 2023-02-20
--------------------

### Added (7 changes)

- **hofund** - Added base Grafana dashboard to `grafana-dashboard` directory. ([Peter Zmilczak](https://github.com/marwin1991) @marwin1991)
- **hofund** - Added git based information to metrics in `hofund_git_info` !12 ([Peter Zmilczak](https://github.com/marwin1991) @marwin1991)
- **hofund** - Added yaml based examples in readme !13 #9 ([Peter Zmilczak](https://github.com/marwin1991) @marwin1991)
- **hofund** - Added your custom connection by extending `AbstractHofundBasicHttpConnection` see README for more details. ([Peter Zmilczak](https://github.com/marwin1991) @marwin1991)
- **logchange** - At the begging of `CHANGELOG.md` added comment which disables auto format in JetBrains IDEs. ([Peter](https://github.com/marwin1991) @marwin1991)
- **logchange** - At the begging of `CHANGELOG.md` added noinspection tag and also added it and formatteroff to `version-summar.md`. ([Peter](https://github.com/marwin1991) @marwin1991)
- **logchange** - Added `add` plugin command to generate empty (when using -Dempty flag) or ask user for input, changelog entry. ([Peter](https://github.com/marwin1991) @marwin1991)

### Changed (3 changes)

- **logchange** - Changed YAML keyword `configuration` to `configurations` ([Peter](https://github.com/marwin1991) @marwin1991)
- **logchange** - Changed the `merge_request` to `merge_requests` to allow using list of numbers instead of just a one number. ([Peter](https://github.com/marwin1991) @marwin1991)
- **logchange** - Migrated project to new GitHub repository. ([Peter](https://github.com/marwin1991) @marwin1991)

### Fixed (1 change)

- **hofund** - Spring Boot 3 compatibility !14 [source](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#auto-configuration-registration) ([Peter Zmilczak](https://github.com/marwin1991) @marwin1991) (@jfoder [LINK](https://github.com/jfoder))

### Configuration changes

| Type: application.properties                                                                                                                                                                                                      |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| <ul><li>hofund</li><li>Added `hofund.git-info.branch` with default value: ``</li><li>Description: Short git commit id, set it to `@git.branch@` and configure `git-commit-id-plugin` see README.md.</li></ul>                     |
| <ul><li>hofund</li><li>Added `hofund.git-info.build.host` with default value: ``</li><li>Description: Short git commit id, set it to `@git.build.host@` and configure `git-commit-id-plugin` see README.md.</li></ul>             |
| <ul><li>hofund</li><li>Added `hofund.git-info.build.time` with default value: ``</li><li>Description: Short git commit id, set it to `@git.build.time@` and configure `git-commit-id-plugin` see README.md.</li></ul>             |
| <ul><li>hofund</li><li>Added `hofund.git-info.commit.id` with default value: ``</li><li>Description: Git commit id, set it to `@git.commit.id@` and configure `git-commit-id-plugin`, see README.md.</li></ul>                    |
| <ul><li>hofund</li><li>Added `hofund.git-info.commit.id-abbrev` with default value: ``</li><li>Description: Short git commit id, set it to `@git.commit.id.abbrev@` and configure `git-commit-id-plugin` see README.md.</li></ul> |
| <ul><li>hofund</li><li>Added `hofund.git-info.dirty` with default value: ``</li><li>Description: Short git commit id, set it to `@git.dirty@` and configure `git-commit-id-plugin` see README.md.</li></ul>                       |



```
</details>

## TODO:

- [x] PR summary
- [x] Changelog entry
- [x] README update
- [x] Tests

### CODE REVIEW

**Comment by marwin1991** [comment]
@witx98 awesome work! 

Do you think it should also work with "unreleased"?

I would like to create summary from many projects containing changes from `unreleased` section

**Review by marwin1991 — APPROVED** [review]
Everything is cool!

**Comment by witx98** [comment]
> @witx98 awesome work!
> 
> Do you think it should also work with "unreleased"?
> 
> I would like to create summary from many projects containing changes from `unreleased` section

I think it does work with `unreleased` @marwin1991

**Comment by marwin1991** [comment]
> > @witx98 awesome work!
> > Do you think it should also work with "unreleased"?
> > I would like to create summary from many projects containing changes from `unreleased` section
> 
> I think it does work with `unreleased` @marwin1991

Good, I will add information to README.md. I have started release proces

**Pull request merged**
