### PR TITLE
Draft: Aggregates

### PR DESCRIPTION
**Pull request by marwin1991**

### CODE REVIEW

**Comment by marwin1991** [comment]
@witx98 @NikodemMarek 

Maybe you will be interested in this idea, which was to allow generating "SUPER CHANGELOG" based on many projects.

It would be useful when you have f.e. 10 projects, and you have to create summary.

There would be command:
```
mvn logchange:aggregate -Dversion:24.3.0
```

Then logchange would look inside config and analyse:
```
aggregates:
  projects:
    - name: hofund
      url: https://github.com/logchange/hofund/archive/refs/heads/master.tar.gz
      type: tar.gz # currently only tar.gz is supported
      input_dir: changelog # the name where dirs with versions are stored for this project
    - name: logchange
      url: https://github.com/logchange/logchange/archive/refs/heads/main.tar.gz
      type: tar.gz
      input_dir: changelog
```

then it would have to download, go to `changelog` folder and then find `version` and at the end create 
summary, f.e. adding at the end of every entry `(project_name)`.

**Comment by witx98** [comment]
The output of this command should generate only basic information about the entry, including the project name, entry title, and type:

```
<!-- @formatter:off -->
<!-- noinspection -->
<!-- Prevents auto format, for JetBrains IDE File > Settings > Editor > Code Style (Formatter Tab) > Turn formatter on/off with markers in code comments  -->

<!-- This file is automatically generate by logchange tool 🌳 🪓 => 🪵 -->
<!-- Visit https://github.com/logchange/logchange and leave a star 🌟 -->
<!-- !!! ⚠️ DO NOT MODIFY THIS FILE, YOUR CHANGES WILL BE LOST ⚠️ !!! -->


[1.0.0] - 2024-10-28
--------------------

### Added (5 changes)

- **hofund** - Added new metric `hofund_os_info` with information about name, version arch of the os running application.
- **hofund** - Added new metric `hofund_java_info` with information about version, vendor and jvm which is running application.
- **hofund** - Added new metric `hofund_web_server_info` with information about type and version of web server.
- **logchange** - Added `dependency_update` changelog entry type.
- **logchange** - Added support for generating Maven's Changes.xml

### Changed (1 change)

- **hofund** - Simplified configuration of metric `hofund_git_info` by reading values from `git.properties` file instead of defining `hofund.git-info`. You can still use this to define custom values for this metric.
```

Or, should it print comprehensive information including important notes, configurations, authors, merge requests, and issues?

```
<!-- @formatter:off -->
<!-- noinspection -->
<!-- Prevents auto format, for JetBrains IDE File > Settings > Editor > Code Style (Formatter Tab) > Turn formatter on/off with markers in code comments  -->

<!-- This file is automatically generate by logchange tool 🌳 🪓 => 🪵 -->
<!-- Visit https://github.com/logchange/logchange and leave a star 🌟 -->
<!-- !!! ⚠️ DO NOT MODIFY THIS FILE, YOUR CHANGES WILL BE LOST ⚠️ !!! -->


[1.0.0] - 2024-10-28
--------------------

### Added (5 changes)

- **hofund** - Added new metric `hofund_os_info` with information about name, version arch of the os running application. !23 #22 ([Peter Zmilczak](https://github.com/marwin1991) @marwin1991)
- **hofund** - Added new metric `hofund_java_info` with information about version, vendor and jvm which is running application. !23 #22 ([Peter Zmilczak](https://github.com/marwin1991) @marwin1991)
- **hofund** - Added new metric `hofund_web_server_info` with information about type and version of web server. !27 #26 ([Peter Zmilczak](https://github.com/marwin1991) @marwin1991)
- **logchange** - Added `dependency_update` changelog entry type. ([Peter](https://github.com/marwin1991) @marwin1991)
- **logchange** - Added support for generating Maven's Changes.xml !126 #103 (@witx98  [LINK](https://github.com/witx98))

### Changed (1 change)

- **hofund** - Simplified configuration of metric `hofund_git_info` by reading values from `git.properties` file instead of defining `hofund.git-info`. You can still use this to define custom values for this metric. !25 #24 ([Peter Zmilczak](https://github.com/marwin1991) @marwin1991)
```
@marwin1991

**Comment by witx98** [comment]
One more question: if one of the aggregated projects doesn’t have a directory for the specified version, should the process fail and list all the invalid projects, or should it generate the changelog and simply omit the missing projects?

**Comment by marwin1991** [comment]
@witx98 

It looks better to print comprehensive information including important notes, configurations, authors, merge requests, and issues. I was wondering about if we can create config for this using placeholders in config file.

Something like
'''yml
    entry_template: "**{{project_name}} - {{entry_title}} and so on....
'''

What do you think @witx98 ?


The second question:

Maybe for now it will be enough to print waring in logs? You are here the boss!

**Comment by witx98** [comment]
We could definitely consider adding a configuration with customizable placeholders as a separate improvement. That would provide more flexibility for formatting entries according to specific needs.

In the meantime, feel free to review this proposal for the [aggregate functionality](https://github.com/logchange/logchange/pull/335) as-is to see if it meets the initial requirements.

As for the warning, I agree – logging a warning is probably a better way. Thanks for the feedback!

@marwin1991

**Pull request merged**
